config/routes.rb
Rails.application.routes.draw do

  resources :wines do
    resources :log_entries
    get 'page/:page', :action => :index, :on => :collection
  end

  root 'wines#index'

end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
  RATINGS = 1..5
  validates :name, :rating, :location, :comments, :tasted_on, presence: true
  validates :rating, inclusion: { in: RATINGS }
  belongs_to :wine
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  VARIETALS = ['Merlot', 'Chianti', 'Chardonnay', 'Cabernet Sauvignon',
   'Champagne', 'Bordeaux Blend', 'Pinot Noir', 'Riesling', 'Cava', 'Pinot Grigio']
  validates :name, :year, :country, presence: true
  validates :year,
    numericality: { only_integer: true },
    if: "year.present?"
  validates :varietal, inclusion: { in: VARIETALS }

  has_many :log_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Don't apply layouts for ajax requests
  layout ->(controller) { controller.request.xhr? ? false : 'application' }
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
  before_action :set_wine

  def index
    @log_entries = @wine.log_entries.order('tasted_on desc')
  end

  def new
    @log_entry = @wine.log_entries.new
  end

  def create
    @log_entry = @wine.log_entries.new(log_entry_params)
    if @log_entry.save
      redirect_to wine_log_entries_path(@wine), success: 'Log Entry saved!'
    else
      render :new
    end
  end

  private

  def set_wine
    @wine = Wine.find(params[:wine_id])
  end

  def log_entry_params
    params.require(:log_entry).permit(:name, :rating, :location, :comments, :tasted_on)
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :destroy, :update]

  def index
    @available_at = Time.now
    @wines = Wine.order(:name).page(params[:page])
  end

  def show
    @wine = Wine.find(params[:id])
  end

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.new(wine_params)
    if @wine.save
      redirect_to @wine
    else
      render :new
    end
  end

  def update
    if @wine.update(wine_params)
      redirect_to @wine
    else
      render :new
    end

  end

  def destroy
    @wine.destroy
    redirect_to wines_url
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :year, :winery, :country, :varietal)
  end

  def set_wine
    @wine = Wine.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
  def formatted_time(time)
    time.strftime("%B %d, %Y at %l:%M %p")
  end
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('Amazing Wines', root_path) %></h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Navigation</h3>
    </div>
    <div class="panel-body">
      <p>
        <%= link_to 'All Wines', wines_path %>
      </p>
      <p>
        <%= link_to 'Create Wine', new_wine_path %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wines <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>

app/views/log_entries/_form.html.erb
<%= form_for( [ @wine, @log_entry ] ) do |f| %>
  <%= render 'shared/validation_errors', object: @log_entry %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, placeholder: 'Name' %><br />
  <%= f.label :location %>
  <%= f.text_field :location, placeholder: 'Location' %><br />
  <%= f.label :rating %>
  <% LogEntry::RATINGS.each do |rating| %>
    <%= f.radio_button :rating, rating %> <%= rating %>
  <% end %><br />
  <%= f.label :tasted_on %>
  <%= date_select(:log_entry, :tasted_on, { include_blank: false }) %><br />
  <%= f.label :comments %><br />
  <%= f.text_area :comments %><br />
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wine_log_entries_path(@wine), id: 'cancel_log_entry' %>
  </p>
<% end %>

app/views/log_entries/index.html.erb
<header>Log Entries for <%= link_to(@wine.name, @wine) %></header>
<ol id="log_entries">
  <% @log_entries.each do |log_entry| %>
    <li>
      <span class="log_entry"><%= pluralize(log_entry.rating, 'rating') %></span>
      <span class="user">by <%= log_entry.name %> </span>
      <span class="date">
        <%= time_ago_in_words(log_entry.tasted_on) %> ago
      </span>
      <span class="location">at <%= log_entry.location %> </span>
      <p>
        &quot;<%= log_entry.comments %>&quot;
      </p>
    </li>
  <% end %>
</ol>

<%= link_to 'Write a Log Entry', new_wine_log_entry_path(@wine),
        remote: true,
        data: { 'update-target' => 'log_entry_form_container' },
        class: 'btn btn-primary' %>

<div id="log_entry_form_container"></div>

app/views/log_entries/new.html.erb
<h1>Write a log entry for <%= link_to(@wine.name, @wine) %></h1>
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="alert <%= alert_class_for(key) %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.
    <br/ >
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
  <%= render 'shared/validation_errors', object: @wine %>
  <%= f.label :name %> <%= f.text_field :name, autofocus: true %><br />
  <%= f.label :year %> <%= f.text_field :year %><br />
  <%= f.label :winery %> <%= f.text_field :winery %><br />
  <%= f.label :country %> <%= f.text_field :country %><br />
  <%= f.label :varietal %>
  <%= f.select(:varietal, Wine::VARIETALS, :prompt => "Pick one") %><br />
  <br />
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wines_path %>
  </p>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing <%= @wine.name %></h1>
<%= render 'form' %>

app/views/wines/index.html.erb
<h1>Wines</h1>
<p>Available as of <%= formatted_time(@available_at) %></p>
<%= page_entries_info @wines %>
<ol>
  <% @wines.each do |wine| %>
    <li>
      <%= link_to(wine.name , wine) %>
      by <%= wine.winery + " (" + wine.varietal  + ")" %>
    </li>
  <% end %>
</ol>
<%= paginate @wines %>

app/views/wines/new.html.erb
<h1>Create New Wine</h1>
<%= render 'form' %>

app/views/wines/show.html.erb
<% content_for :name, @wine.name %>
<article class="wine">
  <header>
    <h2><%= @wine.name %></h2>
  </header>
  <p><label>Winery:</label> <%= @wine.winery %></p>
  <p><label>Year:</label> <%= @wine.year %></p>
  <p><label>Country:</label> <%= @wine.country %></p>
  <p><label>Varietal:</label> <%= @wine.varietal %></p>
</article>

<p>
  Read all
  <%= link_to pluralize(@wine.log_entries.size, 'log entry'),
                        wine_log_entries_path(@wine) %>
</p>
<br />

<%= link_to 'All wines', wines_path %> | <%= link_to 'Edit', edit_wine_path(@wine) %>